# Change these first
owner: jupiter-project # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://jup.io
  - name: Blog
    url: https://blog.jup.io
  - name: Web Wallet
    url: https://nodes.jup.io
  - name: Galileo Blockchain Stats
    url: https://galileo.jup.io
  - name: Project IPFS Gateway
    url: https://gravity.jup.io/ipfs/QmSxJqjPsnHUY9XNBYWVTWHiQuXUvapZtDEL2tBkBSSNsE?filename=Layer%201-AnimatedJup%20(1).mp4
  - name: Project IPFS API
    url: $IPFS_API
  - name: Metis API
    url: $METIS_API

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.jup.io
  # baseUrl: /your-repo-name
  logoUrl: https://uploads-ssl.webflow.com/6065eb30d12de81420326c90/614dec75d2aac68510e25798_JUP%20LOGO.svg
  name: Jupiter
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the Jupiter Project status page which uses **real-time** data from our [GitHub repository](https://github.com/jupiter-project/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
